version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_DEBUG_MODE=true
    ports:
      - "7070:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: 
      context: ./backend
      args: 
        - FLASK_ENV=production
        - WORDNIK_API_KEY={ENTER_KEY}
    ports:
      - "5000:5000"
    restart: always
