version: "3.8"

services:
  postgres:
    env_file:
      - .env
    image: postgres:15
    container_name: wordmorph-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextjs:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordmorph-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/home/node/app
      - /hom/node/app/node_modules
    command: npm run start

volumes:
  postgres_data:
